//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.HistoricoFacturacion = new HashSet<HistoricoFacturacion>();
            this.LineaDetalle = new HashSet<LineaDetalle>();
        }
    
        public long IdFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
    
        public virtual ICollection<HistoricoFacturacion> HistoricoFacturacion { get; set; }
        public virtual ICollection<LineaDetalle> LineaDetalle { get; set; }
    }
}
