//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.LineaDetalle = new HashSet<LineaDetalle>();
        }
    
        public long Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int CantidadInventario { get; set; }
    
        public virtual ICollection<LineaDetalle> LineaDetalle { get; set; }
    }
}
